enum EAuthActions {
  SIGN_IN = "SIGN_IN",
  SIGN_IN_REQUEST = "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE = "SIGN_IN_FAILURE",

  LOG_OUT = "LOG_OUT",
  LOG_OUT_REQUEST = "LOG_OUT_REQUEST",
  LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS",
  LOG_OUT_FAILURE = "LOG_OUT_FAILURE",
}

export { EAuthActions };
