enum ESubjectAction {
  GET_SUBJECT = "GET_SUBJECT",
  GET_SUBJECT_REQUEST = "GET_SUBJECT_REQUEST",
  GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS",
  GET_SUBJECT_FAILURE = "GET_SUBJECT_FAILURE",
}

export { ESubjectAction };
