enum ESourceAction {
  GET_SOURCE = "GET_SOURCE",
  GET_SOURCE_REQUEST = "GET_SOURCE_REQUEST",
  GET_SOURCE_SUCCESS = "GET_SOURCE_SUCCESS",
  GET_SOURCE_FAILURE = "GET_SOURCE_FAILURE",

  GET_ALL_SOURCE = "GET_ALL_SOURCE",
  GET_ALL_SOURCE_REQUEST = "GET_ALL_SOURCE_REQUEST",
  GET_ALL_SOURCE_SUCCESS = "GET_ALL_SOURCE_SUCCESS",
  GET_ALL_SOURCE_FAILURE = "GET_ALL_SOURCE_FAILURE",

  SEARCH_SOURCE = "SEARCH_SOURCE",
  SEARCH_SOURCE_REQUEST = "SEARCH_SOURCE_REQUEST",
  SEARCH_SOURCE_SUCCESS = "SEARCH_SOURCE_SUCCESS",
  SEARCH_SOURCE_FAILURE = "SEARCH_SOURCE_FAILURE",
}

export { ESourceAction };
